### ISSUE TITLE
Using gexec & GinkgoWriter for multiple commands

### ISSUE THREAD

**Issue by kavinderd** [onsi/gomega#115]
I'm new to using Ginkgo/Gomega and am working on writing `ls` in go. In my test I'd like to test the output of my command versus that of the system `ls`. I'm running into an issue with the following code

```
command := exec.Command(pathToLs, "")
session, err := gexec.Start(command, GinkgoWriter, GinkgoWriter)
Ω(err).ShouldNot(HaveOccurred())

commandReal := exec.Command("ls")
sessionReal, err := gexec.Start(commandReal, GinkgoWriter, GinkgoWriter)
Ω(err).ShouldNot(HaveOccurred())

Eventually(string(session.Out.Contents())).Should(Equal(string(sessionReal.Out.Contents())))
```
The test passes I believe because by the time the assertion is evaluated the GinkgoWriter has the same output for both `session` and `sessionReal`. Is there a more appropriate way I should be testing this?

**Comment by onsi** [comment]
Hi @kavinderd,

Each `gexec.Session` object maintains its own internal buffer containing output from the underlying command.  The (optional) `io.Writer` arguments that go to `gexec.Start` are used to allow you to *additionally* pipe the command output to a writer.

Using the [`GinkgoWriter`](http://onsi.github.io/ginkgo/#logging-output) is a good idea because you'll see the command output if you run the test in verbose mode *or* if the test fails.

The actual problem with your test is your use of `Eventually`.  As written your test starts the two different versions of `ls` (in the background, that's how `gexec.Start` works) and then **immediately** asks for the logged output of these two sessions.  `session.Out.Contents()` returns a `[]byte` array that will *never change* so you are basically capturing the output of both commands immediately after invoking them.  I bet they're both coming back empty and the test is succeeding with `Eventually("").Should(Equal(""))` -- which is always, trivially, true.

There are two issues:
1. [`Eventually`](http://onsi.github.io/gomega/#making-asynchronous-assertions) needs to be given an object/function that it can poll.  And it will poll the object/function until the matcher is satisfied.  In your case you pass in an immutable string that will never change.
2. You are fetching the contents immediately after invoking the commands (likely before they've even started running).  You'll need to [wait until the commands exit](http://onsi.github.io/gomega/#gexec-testing-external-processes) before you can make this comparison.

There are two ways to do this.  Here's a test that should fail (and, eventually - once you implement `ls` in Go, pass) correctly:

```golang
command := exec.Command(pathToLs, "")
session, err := gexec.Start(command, GinkgoWriter, GinkgoWriter)
Ω(err).ShouldNot(HaveOccurred())

commandReal := exec.Command("ls")
sessionReal, err := gexec.Start(commandReal, GinkgoWriter, GinkgoWriter)
Ω(err).ShouldNot(HaveOccurred())

session.Wait() // waits for the session to exit
Eventually(sessionReal).Should(gexec.Exit(0)) // equivalent to `session.Wait()` but allows you to assert on exit code

Ω(session.Out.Contents()).Should(Equal(sessionReal.Out.Contents()))
```

Hope that helps.  I'd recommend reading through the Gomega docs to familiarize yourself with how asynchronous assertions and `gexec` work.

**Comment by kavinderd** [comment]
Thanks a lot @onsi for that very thorough answer. It makes a lot of sense. You're right, I did some debugging, and the output of both `.Out.Contents()` was blank. 

I'll be sure to pay better attention to the docs, I completely missed the notion that `gexec.Start()` doesn't actually run the command immediately. 

Thanks for the library, it makes writing my first Go apps much easier.
