### ISSUE TITLE
protobuf dependency

### ISSUE THREAD

**Issue by james-lawrence** [onsi/gomega#123]
do we really want gomega pulling in dependencies that projects may or may not rely on? it looks like something that can be supported via a library.

**Comment by robdimsdale** [comment]
Protobuf is used in [one of the matchers](https://github.com/onsi/gomega/blob/master/ghttp/handlers.go#L155-L179) - if we `go get github.com/onsi/gomega/...` it will pull in all the dependencies, including protobuf, and if we we do `go get github.com/onsi/gomega` it will fail to compile as protobuf is missing.

Are you suggesting removing this protobuf matcher into a separate matchers library?

**Comment by onsi** [comment]
I'm tending to agree.  It would be a backward incompatible change obviously - but the additional dependency is really getting in the way - most people don't go get with the recursive ...

One other option is to add the dependency to the root package to force go to fetch it (_ import) - it's ugly and hacky but would get us past this hump without breaking anything.

**Comment by xoebus** [comment]
I like the `_` import. It's ugly but pragmatic and easily documented. It importantly keeps backwards compatibility until 2.0.

Maybe at 2.0 the Protocol Buffers matchers can be moved into a different package?

**Comment by james-lawrence** [comment]
yes, rob that is what I am suggesting.

I'm mainly trying to prevent it from happening in the future. I wish I had caught that PR to begin with.

**Comment by onsi** [comment]
Am leaning towards the `_` approach in the main package.  I'd happily take a PR to that effect or will try to get time to work on it.

At this point taking the matcher out will break people all over - would prefer to avoid that.

**Comment by james-lawrence** [comment]
I might be able to make some time for it. though I was hoping to work on one of my own libraries, will let you know this weekend.

**Comment by ches** [comment]
👍  to removing the dependency and supporting protobuf matchers via a separate library, or at least a subpackage so that you don't hit the import unless you specifically want to use it.

In going through the ghttp docs and trying it out I was surprised when examples failed due to a new missing test dependency on protobuf, when I have no interest in using protobufs for the application in question. It made me pause to ask if there is really value over plain `net/http/httptest` even though I was already using Gomega, so take that FWIW. No one likes unnecessary (unrelated, even) dependencies foisted on them, plus it opens a possibility for dependency hell as @james-lawrence mentioned for projects that *do* want it (however slim the likelihood may be, these things do happen, and Go doesn't have the most shining of package versioning stories…)

**Comment by ches** [comment]
Looking at other related issues (e.g. #139), I guess it's clear that my vote is to *not* add dependencies to what `go get github.com/onsi/gomega` pulls in, even if they are resolved automatically.

**Comment by jhamon** [comment]
It's 2017 and I ran into this issue with protobuf missing. As a golang noob is was quite confusing. If running `go get github.com/onsi/gomega/...` instead of `go get github.com/onsi/gomega` is all that's needed to avoid this confusion, why don't we update [the docs](http://onsi.github.io/ginkgo/) to show that way of fetching ginkgo?

**Comment by williammartin** [comment]
Wondering if we release a 2.0 soon-ish whether we can sneak this in.

**Comment by williammartin** [comment]
For now we've just decided to document this better in Gomega and Ginkgo. This seems like the best of worlds for now. 

1. Anyone new to Go coming to the docs will get everything they need with a description of how to avoid this if they'd rather not.
1. Anyone who doesn't want the dependency can choose not to get it.
1. We don't break anyone currently using the matcher.

Might consider closing this and revisiting the question when we want to release 2.0.
