### ISSUE TITLE
Gexec signalling tests are flaky

### ISSUE THREAD

**Issue by williammartin** [onsi/gomega#240]
It seems like there are a bunch of signal related tests that are flaky e.g.

https://github.com/onsi/gomega/blob/master/gexec/session_test.go#L292-L299

The reason I suggest this is flaky is that it's entirely dependent on whether the signal is actioned faster than the Expectation is performed. This fails for me sometimes locally but I also found a Travis failure:

https://travis-ci.org/onsi/gomega/builds/130029926

**Comment by kirederik** [comment]
The Travis build failed [here](https://github.com/onsi/gomega/blob/4fc17627b66f18840f3604eec277fe1af7f6d4a5/gexec/session_test.go#L126-L127), not on the highlighted code. We think that both of them suffer from the same malady though.

It seems that the [entire Describe](https://github.com/onsi/gomega/blob/4fc17627b66f18840f3604eec277fe1af7f6d4a5/gexec/session_test.go#L283-L310) can be flaky.

with @nodo

**Comment by gcapizzi** [comment]
The reason this sometimes fails is that the test assumes that the process will take long enough to die, so the assertion will happen *before* the process is actually dead. This is not always the case. In order to fix this, we could:

1. make sure that the process *always* takes a bit longer to die, e.g. by building a fixture binary that traps signals and sleeps for a bit before dying (note that `SIGKILL` is *not* trappable, so this approach would not work for `Kill()`)
1. remove the tests 😄

We think there is value in proving that sending signals is an async operation, but at the same time testing it is impossible for a least one signal, and a bit complicated for the others. 

How do people feel about this?

/cc @nodo

**Comment by williammartin** [comment]
I'm 100% in favour of removing all the `does not wait` tests. We guess the original intention was to get rid of `.Waits`, with a fire and forget signal, but it's now just weird and it'll totally never work. Not worth keeping IMO.

**Comment by gcapizzi** [comment]
Done 😉
