### ISSUE TITLE
New Release with MatchKeys

### ISSUE THREAD

**Issue by adambuckland** [onsi/gomega#337]
Hello :wave:

`MatchKeys` is a very useful matcher that makes life so much easier dealing with maps, and thank you for adding it.

However at the moment, in order to use it, we have to target specific commits or master, which isn't ideal for safety reasons. Are there any plans to cut a new release tag including `MatchKeys`?

Thanks!

**Comment by williammartin** [comment]
I'll release today. Thanks for the bump.

**Comment by adambuckland** [comment]
Blimey, that was quick! Thanks!

**Comment by williammartin** [comment]
If you have a moment, do you think you could test whether the commits in https://github.com/onsi/gomega/pull/330 still work for you? I haven't had a chance to review yet but it would be nice to get it in before releasing since it's a better UX.

Could use you as a guinea 🐷

No worries if you don't have time though :)

**Comment by adambuckland** [comment]
I'm sorry, but I don't today. However, I can tomorrow morning if that's OK?

**Comment by williammartin** [comment]
Here you go https://github.com/onsi/gomega/releases/tag/v1.5.0
