### ISSUE TITLE
Any equivalent methods as gomock.Inorder in Gomega?

### ISSUE THREAD

**Issue by JoeyLuffa** [onsi/gomega#348]
One of the functions I am going to test against have an API call twice with different arguments. I'd like to verify that they're called with different inputs. With GoMocks, I can do:
```
gomock.InOrder(
    mockObj.EXPECT().SomeMethod(1, "first"),
    mockObj.EXPECT().SomeMethod(2, "second"),
)
```
Is there an equivalent method as gomock.Inorder in Gomega? Thanks.

**Comment by williammartin** [comment]
Hi @JoeyLuffa I'm not super familiar with `gomock`. It seems like it is a combination of a mocking library and an assertion library. Since `gomega` is purely for assertions, it would need some separate library (possibly even gomock) to collect information about methods called.

A common pattern we see are people creating fakes with [counterfeiter](https://github.com/maxbrunsfeld/counterfeiter) and then using `gomega` like:

```
Expect(fake.ArgsForCall(0)).To(Equal("first"))
Expect(fake.ArgsForCall(1)).To(Equal("second"))
```

Hope this helps.
