### ISSUE TITLE
go test fails with build error

### ISSUE THREAD

**Issue by rtfmoz2** [onsi/gomega#537]
```
rtfmoz@DESKTOP-H138G2U:/mnt/c/Users/Kevin/Projects/alpaca$ go test
# github.com/samuong/alpaca [github.com/samuong/alpaca.test]
./authenticator_test.go:87:15: undefined: io.ReadAll
FAIL    github.com/samuong/alpaca [build failed]
```

**Comment by rtfmoz2** [comment]
It appears that ReadAll is no longer available under io. Further reading suggests to use ioutil instead.

**Comment by blgm** [comment]
It's the other way around. ioutil was deprecated in Go 1.16, and io.ReadAll was added.

I can't see anything in the error message that suggests this is to do with Gomega. Am I missing something?

**Comment by rtfmoz2** [comment]
I know right, but io.ReadAll stopped working and ioutils.ReadAll works. Go figure.  I don't know how this issue ended up here, I posted it over at alpaca

**Comment by rtfmoz2** [comment]
See this conversations

https://github.com/onsi/gomega/issues/488 and 
https://github.com/onsi/gomega/pull/492

**Comment by blgm** [comment]
I guess it's worth checking the Go version that's being used. It also might be worth checking whether there are any other versions of Go on the system, as sometimes a test might modify the PATH and end up using a different version of Go than you thought you were using.

Gomega uses build tags so that ioutil is used for Go 1.15 and earlier, and io.ReadAll for Go 1.16 and higher. It's possible that this has gone wrong, but the error message is pointing to "./authenticator_test.go:87:15" which I don't think is part of Gomega.

**Comment by rtfmoz2** [comment]
I installed go today and picked up this issue
