### ISSUE TITLE
[Feature] ExpectError

### ISSUE THREAD

**Issue by Airblader** [onsi/gomega#568]
# Proposal

Sometimes we have a function that returns a value + an error, but we are only interested in asserting on the error (since in that case the value will typically be irrelevant or nil). Currently, this requires

```
_, err := Foo()
Expect(err).To(HaveOccurred())
```

`Expect` already provides the convenience of ignoring trailing return values, and using only the first one. Thus, I want to propose adding the "reverse", e.g.

```
func ExpectError(_ any, err error) Assertion {
	return Expect(err)
}

ExpectError(Foo()).To(HaveOccurred())
```

Since Go does not allow `...` arguments followed by a normal argument, this only works for two return values, and thus the following (or something along the lines of) might be needed, too (admittedly this is where it becomes a bit less pretty):

```
func ExpectError3(_, _ any, err error) Assertion { return Expect(err) }
```

This would probably cover the vast majority of cases, and if a function does return even more one would just have to use the "old" way. Admittedly this is something that could be argued over.

I'm wondering whether this little convenience helper (with or without `ExpectError3`) would be accepted?

# Use Case

Just to give context, we have some test utility functions to create certain resources in the database, and they typically look like this (toy code here, of course):

```
func CreateAccount(database Database, name string) (*Account, error) {}
func CreateTransaction(database Database, account, name string, amount int) (*Transaction, error) {}
```

In some tests we care about the returned objects, but in many tests we just want to set up some state and don't need the returned objects, all the while wanting to make sure that the state could actually be set up. This results in annoying blocks like this:

```
var err error
err = CreateAccount(database, "account1")
Expect(err).ToNot(HaveOccurred())
err = CreateAccount(database, "account2")
Expect(err).ToNot(HaveOccurred())
err = CreateTransaction(database, "account1", "t1", 10)
Expect(err).ToNot(HaveOccurred())
err = CreateTransaction(database, "account2", "t1", 10)
Expect(err).ToNot(HaveOccurred())
```

... which would be cut in half with `ExpectError`.

**Comment by thediveo** [comment]
Hi @Airblader, your wish has already been granted some time ago (because it was driving me mad, too). 😁 

Admittedly, it is "slightly" hidden in plain sight:  in [Gomega's documentation, section Handling Errors](https://onsi.github.io/gomega/#handling-errors) please scroll down a little bit until the part that walks you through multi-return value functions with error returns:

```go
// Ω and Expect are exchangeable, but don't tell the ancient Greeks!
Expect(MultipleReturnValuesFunc()).Error().Should(HaveOccurred())
```

We settled on the hopefully more elegant `Error()` chaining method instead of having a separate set of Error-related Expects.

So your example shrinks as you would like to have it down to:

```go
Expect(CreateAccount(database, "account1")).Error().ToNot(HaveOccurred())
Expect(CreateAccount(database, "account2")).Error().ToNot(HaveOccurred())
Expect(CreateTransaction(database, "account1", "t1", 10)).Error().ToNot(HaveOccurred())
Expect(CreateTransaction(database, "account2", "t1", 10)).Error().ToNot(HaveOccurred())
```
If this does solve your use cases, then please close this issue. If it doesn't, then please tell us what you find missing with the existing `Error()` chain method.

**Comment by Airblader** [comment]
Thank you, that's fantastic news, and indeed a nicer API, too!
