### ISSUE TITLE
How to avoid "tons" of `.WithOffset(1).` in larger test helpers?

### ISSUE THREAD

**Issue by thediveo** [onsi/gomega#624]
Lately I'm ending up more and more writing more complex test helpers, that aren't matchers, but setup more complex things and thus tend to get reused in different packages in `BeforeXXX` nodes. In order to provide less cluttered stack traces when things go "boing" I have to liberally add `.WithOffset(1).`.

Do we have a way to specify in a helper that we want to scope all expectations with an implicit offset of 1, or rather, of +1?

**Comment by onsi** [comment]
I've been wondering similar things.  it also makes it hard to write helpers that wrap helpers and so one ends up passing offset offsets and managing way too much fiddly complexity.

I think we could implement the equivalent of `t.Helper()` in Ginkgo (`GinkgoHelper()`?) and then teach it how to excise functions that call `GinkgoHelper()` from the stack.

I've hesitated in the past because I've  naively worried that this could break compatibility with the existing offset stuff.

But as I think about it more deeply: I think I'm wrong and the two could coexist.  Basically Gingko would first honor offset, then take the remaining stack and prune anything that had had `GinkgoHelper()` called in it.

Thoughts?

**Comment by onsi** [comment]
hey! give the latest (as yet unreleased) version of GInkgo a try.  It introduces `GinkgoHelper()` which should make your `WithOffset()` nightmare go away.

**Comment by thediveo** [comment]
Will give it a try! From the added documentation that looks like this is it, thank you very much! My gut feeling is that this can finally retire (while not retracting) `WithOffset`.

**Comment by onsi** [comment]
💯 agreed!

**Comment by onsi** [comment]
this is now in Ginkgo 2.8.0

**Comment by thediveo** [comment]
works like a treat!
